---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: fleet-tenant-app-sync
spec:
  path: ./deploy/base
  sourceRef:
    kind: GitRepository
    name: tenant-t1-commons-repo